/**
 * שם-מדינה (עברית, טקסט חופשי) → קוד ISO 3166-1 alpha-2, כדי לחשב אמוג'י-דגל.
 * אותו סט שמות בדיוק כמו COUNTRY_CURRENCY_MAP (country-currency.ts) — לא
 * מקור-אמת חדש, רק הרחבה של אותה מיפוי-שמות קיים. Best-effort בכוונה: מדינה
 * שלא מזוהה כאן פשוט לא מקבלת דגל, לא זורקת שגיאה ולא מנחשת.
 */
const COUNTRY_ISO_MAP: Record<string, string> = {
  "תאילנד": "TH",
  "וייטנאם": "VN",
  "אינדונזיה": "ID",
  "באלי": "ID",
  "מלזיה": "MY",
  "פיליפינים": "PH",
  "סינגפור": "SG",
  "קמבודיה": "KH",
  "לאוס": "LA",
  "מיאנמר": "MM",
  "הודו": "IN",
  "סרי לנקה": "LK",
  "נפאל": "NP",
  "יפן": "JP",
  "סין": "CN",
  "הונג קונג": "HK",
  "טייוואן": "TW",
  "דרום קוריאה": "KR",
  "קוריאה הדרומית": "KR",
  "מונגוליה": "MN",
  "איחוד האמירויות": "AE",
  "דובאי": "AE",
  "אבו דאבי": "AE",
  "סעודיה": "SA",
  "ערב הסעודית": "SA",
  "קטאר": "QA",
  "בחריין": "BH",
  "כווית": "KW",
  "עומאן": "OM",
  "ירדן": "JO",
  "מצרים": "EG",
  "טורקיה": "TR",
  "קפריסין": "CY",
  "יוון": "GR",
  "איטליה": "IT",
  "צרפת": "FR",
  "ספרד": "ES",
  "פורטוגל": "PT",
  "גרמניה": "DE",
  "הולנד": "NL",
  "בלגיה": "BE",
  "אוסטריה": "AT",
  "אירלנד": "IE",
  "פינלנד": "FI",
  "מלטה": "MT",
  "סלובניה": "SI",
  "סלובקיה": "SK",
  "אסטוניה": "EE",
  "לטביה": "LV",
  "ליטא": "LT",
  "לוקסמבורג": "LU",
  "קרואטיה": "HR",
  "בריטניה": "GB",
  "אנגליה": "GB",
  "הממלכה המאוחדת": "GB",
  "סקוטלנד": "GB",
  "שוויץ": "CH",
  "נורווגיה": "NO",
  "שוודיה": "SE",
  "דנמרק": "DK",
  "איסלנד": "IS",
  "פולין": "PL",
  "צ'כיה": "CZ",
  "הונגריה": "HU",
  "רומניה": "RO",
  "בולגריה": "BG",
  "סרביה": "RS",
  "אלבניה": "AL",
  "מקדוניה": "MK",
  "בוסניה": "BA",
  "מונטנגרו": "ME",
  "מרוקו": "MA",
  "תוניסיה": "TN",
  "רוסיה": "RU",
  "אוקראינה": "UA",
  "גאורגיה": "GE",
  "ארמניה": "AM",
  "אזרבייג'ן": "AZ",
  "קזחסטן": "KZ",
  "אוזבקיסטן": "UZ",
  "ארה\"ב": "US",
  "ארהב": "US",
  "ארצות הברית": "US",
  "אמריקה": "US",
  "קנדה": "CA",
  "מקסיקו": "MX",
  "ברזיל": "BR",
  "ארגנטינה": "AR",
  "צ'ילה": "CL",
  "קולומביה": "CO",
  "פרו": "PE",
  "אורוגוואי": "UY",
  "בוליביה": "BO",
  "קוסטה ריקה": "CR",
  "פנמה": "PA",
  "ג'מייקה": "JM",
  "קובה": "CU",
  "אוסטרליה": "AU",
  "ניו זילנד": "NZ",
  "פיג'י": "FJ",
  "דרום אפריקה": "ZA",
  "קניה": "KE",
  "טנזניה": "TZ",
  "אתיופיה": "ET",
  "ישראל": "IL",
};

function normalizeCountryName(name: string): string {
  return name.trim().replace(/\s+/g, " ");
}

/** אמוג'י-דגל מקוד ISO בן 2 אותיות — נוסחת regional-indicator, בלי ספרייה חיצונית. */
function isoToFlagEmoji(iso2: string): string {
  return Array.from(iso2.toUpperCase())
    .map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65))
    .join("");
}

/** מחזיר אמוג'י-דגל לפי שם-מדינה חופשי, או null אם השם לא מזוהה (לא מנחש). */
export function countryFlagEmoji(countryName: string | null | undefined): string | null {
  if (!countryName) return null;
  const iso = COUNTRY_ISO_MAP[normalizeCountryName(countryName)];
  return iso ? isoToFlagEmoji(iso) : null;
}

/** קוד-מטבע (ISO 4217, למשל "THB") → קוד-ISO של מדינה מייצגת, לדגל ליד שערי-
 * חליפין. "EU" בכוונה (לא מדינה אמיתית) — Unicode מגדיר את 🇪🇺 כרצף-דגל תקני
 * למרות זאת, בדיוק בשביל המקרה הזה (מטבע-רב-מדינות). */
const CURRENCY_TO_ISO: Record<string, string> = {
  THB: "TH",
  VND: "VN",
  IDR: "ID",
  MYR: "MY",
  PHP: "PH",
  SGD: "SG",
  KHR: "KH",
  LAK: "LA",
  MMK: "MM",
  INR: "IN",
  LKR: "LK",
  NPR: "NP",
  JPY: "JP",
  CNY: "CN",
  HKD: "HK",
  TWD: "TW",
  KRW: "KR",
  MNT: "MN",
  AED: "AE",
  SAR: "SA",
  QAR: "QA",
  BHD: "BH",
  KWD: "KW",
  OMR: "OM",
  JOD: "JO",
  EGP: "EG",
  TRY: "TR",
  EUR: "EU",
  GBP: "GB",
  CHF: "CH",
  NOK: "NO",
  SEK: "SE",
  DKK: "DK",
  ISK: "IS",
  PLN: "PL",
  CZK: "CZ",
  HUF: "HU",
  RON: "RO",
  BGN: "BG",
  RSD: "RS",
  ALL: "AL",
  MKD: "MK",
  BAM: "BA",
  MAD: "MA",
  TND: "TN",
  RUB: "RU",
  UAH: "UA",
  GEL: "GE",
  AMD: "AM",
  AZN: "AZ",
  KZT: "KZ",
  UZS: "UZ",
  USD: "US",
  CAD: "CA",
  MXN: "MX",
  BRL: "BR",
  ARS: "AR",
  CLP: "CL",
  COP: "CO",
  PEN: "PE",
  UYU: "UY",
  BOB: "BO",
  CRC: "CR",
  PAB: "PA",
  JMD: "JM",
  CUP: "CU",
  AUD: "AU",
  NZD: "NZ",
  FJD: "FJ",
  ZAR: "ZA",
  KES: "KE",
  TZS: "TZ",
  ETB: "ET",
  ILS: "IL",
};

/** מחזיר אמוג'י-דגל לפי קוד-מטבע (ISO 4217), או null אם לא מזוהה. */
export function currencyFlagEmoji(currencyCode: string | null | undefined): string | null {
  if (!currencyCode) return null;
  const iso = CURRENCY_TO_ISO[currencyCode.toUpperCase()];
  return iso ? isoToFlagEmoji(iso) : null;
}
