import type { PlaceCategory } from "@travel-app/shared-types";
import {
  BedDouble,
  UtensilsCrossed,
  Coffee,
  Martini,
  Building2,
  ShoppingBag,
  Sparkles,
  Landmark,
  PartyPopper,
  Umbrella,
  Trees,
  Waves,
  Droplets,
  Mountain,
  Store,
  Plane,
  Anchor,
  TrainFront,
  Hospital,
  Pill,
  Star,
  Car,
  MapPin,
  type LucideIcon,
} from "lucide-react";

export const PLACE_CATEGORY_LABELS: Record<PlaceCategory, string> = {
  hotel: "מלון",
  restaurant: "מסעדה",
  cafe: "בית קפה",
  bar: "בר",
  mall: "קניון",
  shop: "חנות",
  massage: "מסאז׳",
  attraction: "אטרקציה",
  entertainment: "בילוי",
  beach: "חוף",
  nature: "טבע",
  river: "נחל",
  waterfall: "מפל",
  viewpoint: "תצפית",
  market: "שוק",
  airport: "שדה תעופה",
  port: "נמל",
  train_station: "תחנת רכבת",
  hospital: "בית חולים",
  pharmacy: "בית מרקחת",
  chabad_house: "בית חב״ד",
  car_rental_company: "חברת השכרה",
  other: "אחר",
};

// chabad_house משתמש ב-Star כ-placeholder — אין אייקון דתי-ספציפי ב-Lucide (ספרייה
// חילונית). ראה DECISIONS.md — ממתין להכרעה סופית של המשתמש אם נדרש אייקון ייעודי.
export const PLACE_CATEGORY_ICONS: Record<PlaceCategory, LucideIcon> = {
  hotel: BedDouble,
  restaurant: UtensilsCrossed,
  cafe: Coffee,
  bar: Martini,
  mall: Building2,
  shop: ShoppingBag,
  massage: Sparkles,
  attraction: Landmark,
  entertainment: PartyPopper,
  beach: Umbrella,
  nature: Trees,
  river: Waves,
  waterfall: Droplets,
  viewpoint: Mountain,
  market: Store,
  airport: Plane,
  port: Anchor,
  train_station: TrainFront,
  hospital: Hospital,
  pharmacy: Pill,
  chabad_house: Star,
  car_rental_company: Car,
  other: MapPin,
};
